name: multiple pipeline
on:
	push:
		branches:
			- main
      
	schedule:
		- cron: "0 10 * * 2,4"
	
	pull_request:
		branches:
			- main		
	
	workflow_dispatch:
	
jobs:
	
	on-push:
	if: github.event-name = push
	runs-on: ubuntu-latest
	steps:
		- name: push print
		  run: echo "on push"
	
	on-schedule:
	if: github.event-name = schedule
	runs-on: ubuntu-latest
	steps:
		- name: schedule print
		  run: echo "on schedule"
		  
	workflow_dispatch:
	if: github.event-name = workflow_dispatch
	runs-on: ubuntu-latest
	steps:
		- name: workflow_dispatch print
		  run: echo "workflow_dispatch"
	
	on-pullrequest:
	if: github.event-name = pullrequest && github.action = closed
	runs-on: ubuntu-latest
	steps:
		- name: pullrequest print
		  run: echo " pullrequest printing" 