name: print message
on:
    push: 
        branches:
            - main

jobs:
    print_hello:
        runs-on: ubuntu-latest
        steps:
            - name: print hello world
              run: echo "Hello World"

            - name:  print date
              run: date